sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- 8 # stable
- 6 # LTS
- 4 # maintenance
before_script:
- npm prune
after_success:
- npm run coverage:upload
- npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
